[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fivetwo"
version = "0.1"
description = "Card shuffle and analysis program."
authors = [
  { email = "project.testing010@gmail.com" }
]
dependencies = [
  "numpy==2.4.6",
  "ipykernel==7.3.0",
  "plotly==6.9.0",
  "pandas==3.0.3"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
